// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFgji5fKp8xOMXW-5-t-FNgoLCnXAynU',
    appId: '1:887427559532:web:d14d2ee7ade2b343822849',
    messagingSenderId: '887427559532',
    projectId: 'posturesense-4dfcb',
    authDomain: 'posturesense-4dfcb.firebaseapp.com',
    storageBucket: 'posturesense-4dfcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdlZ8qlAjGWtkZe1lb_fFs3uCDx-zYdeo',
    appId: '1:887427559532:android:97ba80c7e49823b9822849',
    messagingSenderId: '887427559532',
    projectId: 'posturesense-4dfcb',
    storageBucket: 'posturesense-4dfcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGTDQnCrdpUK1lIgOxfghrUtqXn1zJsM',
    appId: '1:887427559532:ios:5610c5894a98cfc9822849',
    messagingSenderId: '887427559532',
    projectId: 'posturesense-4dfcb',
    storageBucket: 'posturesense-4dfcb.firebasestorage.app',
    iosBundleId: 'com.example.postureSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzGTDQnCrdpUK1lIgOxfghrUtqXn1zJsM',
    appId: '1:887427559532:ios:5610c5894a98cfc9822849',
    messagingSenderId: '887427559532',
    projectId: 'posturesense-4dfcb',
    storageBucket: 'posturesense-4dfcb.firebasestorage.app',
    iosBundleId: 'com.example.postureSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlFgji5fKp8xOMXW-5-t-FNgoLCnXAynU',
    appId: '1:887427559532:web:312b3ce792fc9f15822849',
    messagingSenderId: '887427559532',
    projectId: 'posturesense-4dfcb',
    authDomain: 'posturesense-4dfcb.firebaseapp.com',
    storageBucket: 'posturesense-4dfcb.firebasestorage.app',
  );
}
